# Generated by Django 3.2.7 on 2023-12-27 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermanage',
            name='displayname',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
