# Generated by Django 5.0 on 2024-04-30 14:22

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManageApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameMode', models.TextField(default='classic')),
                ('scoredGoals', models.IntegerField(default=0)),
                ('concededGoals', models.IntegerField(default=0)),
                ('ballTouched', models.IntegerField(default=0)),
                ('longestRoundTime', models.IntegerField(default=0)),
                ('shortestRoundTime', models.IntegerField(default=0)),
                ('allRoundTimes', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None)),
                ('catchedPowerUps', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('enemy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player2_stats', to='userManageApp.usermanage')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_stats', to='userManageApp.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player1_stats', to='userManageApp.usermanage')),
            ],
        ),
    ]
