# Generated by Django 5.0 on 2024-05-08 11:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManageApp', '0002_matchstats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchstats',
            name='shortestRoundTime',
            field=models.IntegerField(default=999999999),
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.SmallIntegerField(default=2)),
                ('name', models.TextField(default='NULL')),
                ('mode', models.TextField(default='classic')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='userManageApp.usermanage')),
                ('finalMatch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finalMatch', to='userManageApp.game')),
                ('finalMatchPlayer1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finalMatchPlayer1', to='userManageApp.usermanage')),
                ('finalMatchPlayer2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finalMatchPlayer2', to='userManageApp.usermanage')),
                ('p1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p1', to='userManageApp.usermanage')),
                ('p2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p2', to='userManageApp.usermanage')),
                ('p3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p3', to='userManageApp.usermanage')),
                ('p4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p4', to='userManageApp.usermanage')),
                ('semiMatch1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semiMatch1', to='userManageApp.game')),
                ('semiMatch2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semiMatch2', to='userManageApp.game')),
                ('thirdPlaceMatch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thirdPlaceMatch', to='userManageApp.game')),
                ('thirdPlaceMatchPlayer1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thirdPlacePlayer1', to='userManageApp.usermanage')),
                ('thirdPlaceMatchPlayer2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thirdPlacePlayer2', to='userManageApp.usermanage')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='userManageApp.usermanage')),
            ],
        ),
    ]
